version: '3.8'

services:
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./UniHub:/app_host:ro
    command: [ "postgres", "-c", "fsync=off" ]

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./UniHub
      dockerfile: ./dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./UniHub:/app
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=true
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: ["./importDB.sh"]

  celery:
    build:
      context: ./UniHub
      dockerfile: ./dockerfile
    command: celery -A UniHub worker --loglevel=info
    volumes:
      - ./UniHub:/app
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_HOST=db  # Make sure this matches what's in your Django settings
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase  # Add this line
    depends_on:
      - db  # Ensure this is present
      - redis

  frontend:
    build: ./ReactFrontend
    ports:
      - "5173:5173"
    volumes:
      - ./ReactFrontend/certs:/app/certs
    depends_on:
      - backend

volumes:
  pgdata:
