services:
  backend:
    build:
      context: ./UniHub  # Build context is the UniHub directory
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SQLITE_PATH=/app/db.sqlite3  # Path within the container
    volumes:
      - sqlite_data:/app  # Mount volume at /app

  frontend:
    build: ./ReactFrontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  sqlite_data:


