version: '3.8'
services:
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./UniHub:/app_host:ro
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro # Mount the script
    command: [ "postgres", "-c", "fsync=off" ] # Add any custom PostgreSQL commands here

  backend:
    build:
      context: ./UniHub # Build context is the UniHub directory
      dockerfile: ./dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./UniHub:/app
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=true
    depends_on:
      - db
    command: ["./waitForDB.sh", "db", "sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000" ]

  frontend:
    build: ./ReactFrontend
    ports:
      - "5173:5173"
    volumes:
      - ./ReactFrontend/certs:/app/certs # Map local certs directory to container
    depends_on:
      - backend

volumes:
  pgdata:
