version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./UniHub # Build context is the UniHub directory
      dockerfile: ./dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_NAME=mydatabase
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    volumes:
      - ./UniHub:/app
    command: ["./waitForDB.sh", "db", "sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

  frontend:
    build: ./ReactFrontend
    ports:
      - "5173:5173"
    volumes:
      - ./ReactFrontend/certs:/app/certs # Map local certs directory to container
    depends_on:
      - backend

volumes:
  pgdata:
