version: '3.8'
services:
  backend:
    build:
      context: ./UniHub # Build context is the UniHub directory
      dockerfile: ./dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SQLITE_PATH=/app/db.sqlite3 # Path within the container
    volumes:
      - sqlite_data:/app # Mount volume at /app

  frontend:
    build: ./ReactFrontend
    ports:
      - "5173:5173"
    volumes:
      - ./ReactFrontend/certs:/app/certs # Map local certs directory to container
    depends_on:
      - backend

volumes:
  sqlite_data:
