# Use an official Python image
FROM python:3.10

WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project files
COPY . /app/
COPY . .

# Ensure the SQLite database file is stored persistently
VOLUME [ "/app/data/db.sqlite3" ]

# Expose Django's default port
EXPOSE 8000

CMD python manage.py migrate && python manage.py runserver 0.0.0.0:8000