# Generated by Django 5.1.6 on 2025-03-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_groups_account_is_active_account_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='account',
            name='firstName',
            field=models.CharField(default='Test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='lastName',
            field=models.CharField(default='Tester', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='pfp',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_pics/'),
        ),
    ]