# Generated by Django 5.1.6 on 2025-03-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_groups_account_is_active_account_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='account',
            name='firstName',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='lastName',
            field=models.CharField(default='person', max_length=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='pfp',
            field=models.ImageField(default='default.webp', max_length=500, upload_to='profile_pics'),
        ),
    ]
