# Generated by Django 5.1.6 on 2025-03-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_account_bio_account_firstname_account_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pfp',
            field=models.ImageField(default='default.webp', max_length=500, upload_to='profile_pics'),
        ),
    ]
