# Generated by Django 5.1.6 on 2025-03-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_society_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='numOfInterestedPeople',
            field=models.IntegerField(default=0),
        ),
    ]
