# Generated by Django 5.1.6 on 2025-03-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_account_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.CharField(default='This is an event', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Event', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='numOfInterestedPeople',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='society',
            name='numOfInterestedPeople',
            field=models.IntegerField(default=0),
        ),
    ]
