# Generated by Django 5.1.6 on 2025-03-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_details_event_name_event_numofinterestedpeople_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endTime',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startTime',
            new_name='startDate',
        ),
    ]
