# Generated by Django 5.1.6 on 2025-03-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_endtime_event_enddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endDate',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startDate',
            new_name='startTime',
        ),
    ]
