# Generated by Django 5.1.7 on 2025-03-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_enddate_event_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountID',
            field=models.IntegerField(default=101010),
            preserve_default=False,
        ),
    ]
