# Generated by Django 5.1.7 on 2025-03-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_account_accountid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountID',
            field=models.IntegerField(unique=True),
        ),
    ]
