# Generated by Django 5.1.6 on 2025-03-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_society_numofinterestedpeople'),
        ('main', '0011_alter_society_name'),
    ]

    operations = [
    ]
