# Generated by Django 5.1.7 on 2025-03-31 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_merge_20250331_1349'),
        ('main', '0013_alter_society_name'),
    ]

    operations = [
    ]
