# Generated by Django 5.1.6 on 2025-03-31 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_merge_20250331_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='members',
        ),
    ]
