# Generated by Django 5.2 on 2025-05-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
