# Generated by Django 5.2 on 2025-05-07 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_account_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='members',
            field=models.ManyToManyField(related_name='societies', to=settings.AUTH_USER_MODEL),
        ),
    ]
