# Generated by Django 5.2 on 2025-05-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_account_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='account',
            name='course',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('ENG', 'Engineering'), ('BUS', 'Business')], max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='year_of_course',
            field=models.CharField(blank=True, choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('PG', 'Postgraduate')], max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='main.interesttag'),
        ),
    ]
