# Generated by Django 5.2 on 2025-05-07 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_interesttag_account_address_account_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_sent', to=settings.AUTH_USER_MODEL)),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_account', 'to_account')},
            },
        ),
    ]
