# Generated by Django 5.1.6 on 2025-05-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_society_members'),
        ('main', '0019_alter_notification_recipient'),
    ]

    operations = [
    ]
