# Generated by Django 5.2 on 2025-05-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_notification_recipient'),
        ('main', '0019_friendrelation'),
    ]

    operations = [
    ]
