# Generated by Django 5.2.1 on 2025-05-08 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_merge_20250507_2054'),
        ('main', '0020_scheduledeventnotification'),
    ]

    operations = [
    ]
