# Generated by Django 5.2.1 on 2025-05-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_event_online_liveeventchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='events', to='main.interesttag'),
        ),
        migrations.AddField(
            model_name='post',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='posts', to='main.interesttag'),
        ),
        migrations.AddField(
            model_name='society',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='societies', to='main.interesttag'),
        ),
    ]
