# Generated by Django 5.2.1 on 2025-05-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='pfp',
            field=models.ImageField(default='default.webp', upload_to=''),
        ),
    ]
