# Generated by Django 5.2.1 on 2025-05-08 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_society_pfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('public', 'Public'), ('members_only', 'Members Only'), ('admin_only', 'Admin Only')], default='public', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.postvisibility'),
        ),
    ]
