# Generated by Django 5.2.1 on 2025-05-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_postvisibility_post_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='members',
        ),
    ]
