# Generated by Django 5.2.1 on 2025-05-08 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_account_year_of_course'),
        ('main', '0030_post_image'),
    ]

    operations = [
    ]
