# Generated by Django 5.2.1 on 2025-05-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_merge_20250508_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvisibility',
            name='name',
            field=models.CharField(choices=[('public', 'Public'), ('members_only', 'Members Only'), ('admins', 'Admins Only')], default='public', max_length=20),
        ),
    ]
