# Generated by Django 5.2.1 on 2025-05-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='course',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('ENG', 'Engineering'), ('BUS', 'Business')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='year_of_course',
            field=models.CharField(blank=True, choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('PG', 'Postgraduate')], max_length=20, null=True),
        ),
    ]
