from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.urls import path
from main import signup, views, Profile, society, Events, post, searchBar, notifications, liveChat, friends

urlpatterns = [
    path('signup/', signup.SignupView, name='signup'),
    path('choices/', views.get_choices, name='get_choices'),
    path('login/', views.CustomTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path('authenticated/', views.is_authenticated),
    path('token/refresh/', views.CustomRefreshTokenView.as_view(), name="token_refresh"),
    path('logout/', views.logout),
    path('admin_check/', views.is_admin),
    path('Profile/Settings/', Profile.UpdateProfileView),
    path('Profile/Delete/', Profile.deleteProfile),
    path('Profile/<str:account_ID>/delete/', Profile.deleteProfile),
    path('Profile/<str:account_ID>/', Profile.getAccountDetails),
    path('Profile/<str:account_ID>/uploadpfp/', Profile.upload_profile_picture, name='upload_profile_picture'),
    path('Societies/', society.getAllSocieties, name='society-list'),
    path('Societies/CreateSociety/', society.society_create, name='society-create'),
    path('Societies/<str:society_name>/', society.getSocietyDetails, name='society-detail'),
    path('Societies/<str:society_name>/UpdateSociety/', society.UpdateSocietyView, name="update-society"),
    path('Societies/<str:society_name>/DeleteSociety/', society.DeleteSocietyView, name="delete-society"),
    path('Societies/<str:society_name>/join/', society.join_society, name='join-society'),
    path('Societies/<str:society_name>/leave/', society.leave_society, name='leave-society'),
    path('Societies/<str:society_name>/promote/<int:member_id>/', society.promote_member, name='promote-member'),
    path('Societies/<str:society_name>/demote/<int:member_id>/', society.demote_member, name='demote-member'),
    path('Societies/<str:society_name>/kick/<int:member_id>/', society.kick_member, name='kick-member'),
    path('Societies/<str:society_name>/CreateEvent/', Events.CreateEvent),
    path('Societies/<str:society_name>/Events/', Events.getAllEvents),
    path('Societies/<str:society_name>/IsSocietyAdmin/', views.is_society_admin),
    path('Societies/<str:society_name>/<int:eventID>/DeleteEvent/', Events.deleteEvent),
    path('Societies/<str:society_name>/<int:eventID>/UpdateEvent/', Events.UpdateEvent),
    path('Societies/<str:society_name>/<int:eventID>/', Events.getSingleEvent),
    path('GetSocietyFromEvent/<int:eventID>/', Events.getSocietyFromEvent),
    path('Societies/<str:society_name>/<int:eventID>/Join/', Events.join_event),
    path('Societies/<str:society_name>/<int:eventID>/Leave/', Events.leave_event),
    path('Societies/<str:society_name>/<int:eventID>/CheckInterest/', Events.check_interest),
    path('Societies/<str:society_name>/members/', society.getmembers, name='get_society_members_via_relation'),
    path('Societies/<str:society_name>/posts/', post.get_society_posts, name="get_society_posts"),
    path('Societies/<str:society_name>/posts/create/', post.create_post, name="create_post"),
    path('Societies/<str:society_name>/posts/update/<int:post_id>/', post.update_post, name="update-post"),
    path('Societies/<str:society_name>/posts/delete/<int:post_id>/', post.delete_post, name="delete-post"),
    path('Societies/<str:society_name>/posts/can_delete/<int:post_id>/', post.can_delete_post),
    path('posts/friends/', post.get_friends_posts, name="get_friends_posts"),
    path('notifications/', notifications.get_notifications),
    path('notificationBell/', notifications.get_unread_notification_quantity),
    path('notifications/<int:notificationID>/', notifications.mark_notification_as_read),
    path('search/', searchBar.search, name='search'),
    path('<int:eventID>/liveChat/talk/', liveChat.talkInChat),
    path('<int:eventID>/liveChat/', liveChat.getAllMessages),
    path('<str:society_name>/<int:eventID>/liveChat/sendFinalMessage/', liveChat.sendFinalMessage),
    path('<str:society_name>/<int:eventID>/liveChat/<int:chatID>/delete/', liveChat.deleteChat),
    path('<int:eventID>/hasChatEnded/', liveChat.hasChatEnded),
    path('friends/send/<int:to_account_id>/', friends.send_friend_request, name='send_friend_request'),
    path('friends/accept/<int:from_account_id>/', friends.accept_friend_request, name='accept_friend_request'),
    path('friends/decline/<int:from_account_id>/', friends.decline_friend_request, name='decline_friend_request'),
    path('friends/remove/<int:account_id>/', friends.remove_friend, name='remove_friend'),
    path('friends/list/', friends.list_friends, name='list_friends'),
    path('<str:society_name>/<int:personID>/', society.IsPersonInSociety),
    path('confirmEmail/', signup.confirmEmail),
]
