from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.urls import path
from main import signup, views, Profile, society, Events, post, searchBar

urlpatterns = [
    path('signup/', signup.SignupView, name='signup'),
    path('login/', views.CustomTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path('authenticated/', views.is_authenticated),
    path('token/refresh/', views.CustomRefreshTokenView.as_view(), name="token_refresh"),
    path('logout/', views.logout),
    path('admin_check/', views.is_admin),
    path('Profile/Settings/', Profile.UpdateProfileView),
    path('Profile/Delete/', Profile.deleteProfile),
    path('Profile/<str:account_ID>/', Profile.getAccountDetails),
    path('Societies/', society.getAllSocieties, name='society-list'),
    path('Societies/CreateSociety', society.society_create, name='society-create'),
    path('Societies/<str:society_name>/', society.getSocietyDetails, name='society-detail'),
    path('Societies/<str:society_name>/UpdateSociety/', society.UpdateSocietyView, name="update-society"),
    path('Societies/<str:society_name>/DeleteSociety/', society.DeleteSocietyView, name="delete-society"),
    path('Societies/<str:society_name>/join/', society.join_society, name='join-society'),
    path('Societies/<str:society_name>/leave/', society.leave_society, name='leave-society'),
    path('Societies/<str:society_name>/promote/<int:member_id>/', society.promote_member, name='promote-member'),
    path('Societies/<str:society_name>/demote/<int:member_id>/', society.demote_member, name='demote-member'),
    path('Societies/<str:society_name>/kick/<int:member_id>/', society.kick_member, name='kick-member'),
    path('Societies/<str:society_name>/CreateEvent/', Events.CreateEvent),
    path('Societies/<str:society_name>/Events/', Events.getAllEvents),
    path('Societies/<str:society_name>/IsSocietyAdmin/', views.is_society_admin),
    path('Societies/<str:society_name>/<int:eventID>/DeleteEvent/', Events.deleteEvent),
    path('Societies/<str:society_name>/<int:eventID>/UpdateEvent/', Events.UpdateEvent),
    path('Societies/<str:society_name>/<int:eventID>/', Events.getSingleEvent),
    path('GetSocietyFromEvent/<int:eventID>/', Events.getSocietyFromEvent),
    path('Societies/<str:society_name>/<int:eventID>/Join/', Events.join_event),
    path('Societies/<str:society_name>/<int:eventID>/Leave/', Events.leave_event),
    path('Societies/<str:society_name>/members/', society.getmembers, name='society-members'),
    path('Societies/<str:society_name>/posts/', post.get_society_posts, name="get_society_posts"),
    path('Societies/<str:society_name>/posts/create/', post.create_post, name="create_post"),
    path('Societies/<str:society_name>/posts/update/<int:post_id>/', post.update_post, name="update-post"),
    path('Societies/<str:society_name>/posts/delete/<int:post_id>/', post.delete_post, name="delete-post"),
    path('posts/friends/', post.get_friends_posts, name="get_friends_posts"),
    path('search/', searchBar.search, name='search'),
]
